# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'nuget'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Europe/Paris'
    groups:
      microsoft-patch-updates:
        patterns:
          - 'Microsoft.*'
        update-types:
          - 'patch'
      microsoft-minor-updates:
        patterns:
          - 'Microsoft.*'
        update-types:
          - 'minor'
      microsoft-major-updates:
        patterns:
          - 'Microsoft.*'
        update-types:
          - 'major'
    commit-message:
      prefix: 'nuget'
    labels:
      - 'nuget'
      - 'dependencies'

  - package-ecosystem: 'nuget'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'Europe/Paris'
    ignore:
      - dependency-name: 'Microsoft:*'
    commit-message:
      prefix: 'nuget'
    labels:
      - 'nuget'
      - 'dependencies'
